[project]
name = "data-receiver"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "duckdb>=1.2.2",
    "flask>=3.1.0",
    "ipython>=8.18.1",
    "peewee>=3.18.1",
    "psycopg2>=2.9.10",
]
